markdown: kramdown
url: https://ismailkuru.github.io
title: Ismail Kuru
author: Ismail Kuru
description: Personal Website
avatar: profile.jpg
email: ik335@drexel.edu
github: ismailkuru 
twitter: isokuru
linkedin: ismail-kuru-a8aa09103 
permalink: /blog/:year/:month/:day/:title

# needed for travis-ci build
exclude: [vendor]
