# top level stuff you probably don't need to touch
highlighter: rouge 
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true


# edit here to achieve your personal greatness
url: http://kirshanthans.github.io/
baseurl: /
title: Kirshanthan Sundararajah
author: Kirshanthan Sundararajah 
description: Personal Blog and Resume
avatar: profile.png
email: ksundar@purdue.edu
github: kirshanthans # username
twitter: kirshanthan
linkedin: kirshanthan 
google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]
