markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: https://kirshanthans.github.io
title: Kirshanthan Sundararajah
author: Kirshanthan Sundararajah 
description: Personal Blog and Resume
avatar: profile.png
email: ksundar@purdue.edu
github: kirshanthans 
twitter: kirshanthan
linkedin: kirshanthan 
scholar: "citations?hl=en&user=knUrjrMAAAAJ"

# needed for travis-ci build
exclude: [vendor]
